NewsDotNet.WebUI/Areas/Admin/Controllers/AdminArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NewsDotNet.DomainModel.Entities;
using NewsDotNet.DomainModel.Abstract;
using NewsDotNet.WebUI.Areas.Admin.Mappers;
using NewsDotNet.WebUI.Areas.Admin.Models;
using System.IO;
using Newtonsoft.Json;
using NewsDotNet.WebUI.Infrastracture;
using Microsoft.AspNet.Identity.Owin;
using System.Threading.Tasks;
using NewsDotNet.WebUI.Models;
using System.Text.RegularExpressions;
using NewsDotNet.WebUI.Hubs;

namespace NewsDotNet.WebUI.Areas.Admin.Controllers
{
    [Authorize]
    [DenyBlocked]
    [DenyIfPasswordChangeRequired]
    public class AdminArticlesController : Controller
    {
        private IArticlesRepository _articleRepo;
        private ITagsRepository _tagsRepo;
        private IMapper _modelMapper;

        public AdminArticlesController(IArticlesRepository articleRepo, ITagsRepository tagsRepo, IMapper modelMapper)
        {
            _articleRepo = articleRepo;
            _tagsRepo = tagsRepo;
            _modelMapper = modelMapper;
        }

        public ActionResult List(IEnumerable<int> articleIds)
        {
            //seletct only articles with ids form the list
            var result = _articleRepo.All().Where(article => articleIds.Any(id => id == article.Id)).ToList();

            var jsonSettings = new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore };

            var convertedResult = JsonConvert.SerializeObject(result, jsonSettings);

            return Content(convertedResult, "application/json");
        }

        public ActionResult PagingList(int page = 1, int itemsPerPage = 10)
        {
            var publishedArticles = _articleRepo.All().Where(a => a.State == ArticleStates.Published);
            var articlesOnPage = publishedArticles.Skip((page - 1) * itemsPerPage).Take(itemsPerPage).ToList();
            var pagingInfo = new PagingInfo
            {
                CurrentPage = page,
                ItemsPerPage = itemsPerPage,
                TotalItems = publishedArticles.Count()
            };

            var result = new ArticleListViewModel
            {
                Articles = articlesOnPage,
                PagingInfo = pagingInfo
            };

            var jsonSettings = new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore };

            var convertedResult = JsonConvert.SerializeObject(result, jsonSettings);
            return Content(convertedResult, "application/json");
        }

        [HttpGet]
        [Authorize(Roles="User, Editor, Administrator")]
        public ActionResult New()
        {
            var article = new ArticleViewModel();
            ViewBag.Action = ActionType.NewArticle;
            return View("ArticleEditor", article);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User, Editor, Administrator")]
        public async Task<ActionResult> New(ArticleViewModel newArticleView, HttpPostedFileBase titleImage)
        {
            CheckAddressNameAvailability(newArticleView.AddressName, newArticleView.Id);
            if (ModelState.IsValid)
            {
                var article = _modelMapper.Map<ArticleViewModel, Article>(newArticleView);
                article.CreatedTime = DateTime.Now;
                article.LastChangedTime = DateTime.Now;
                article.Tags = TagStringToList(newArticleView.TagsString);
                article.Body = Regex.Replace(article.Body, @"=([0-9])+px", "");
                SaveUploadedImage(article, titleImage);

                var author = await UserManager.FindByNameAsync(User.Identity.Name);
                article.AuthorId = author.Id;

                _articleRepo.Add(article);
                return RedirectToAction("Index", "AdminHome");
            }
            ViewBag.Action = ActionType.NewArticle;
            return View("ArticleEditor", newArticleView);
        }

        [HttpGet]
        public async Task<ActionResult> Edit(string addressName)
        {
            var article = _articleRepo.GetByAddressName(addressName);
            if (null == article)
                return View("Http404", "/Admin" as object);
            if (await UserCanEditArticle(article))
            {
                var articleView = _modelMapper.Map<Article, ArticleViewModel>(article);
                articleView.TagsString = TagListToString(article.Tags);
                ViewBag.Action = ActionType.EditArticle;

                bool isEditedByYou;
                string lockerMessage = ArticleEditorHub.GetLockerMessage(article.Id, User.Identity.Name, out isEditedByYou);
                if (!isEditedByYou)
                    ViewBag.LockerMessage = lockerMessage;
                
                return View("ArticleEditor", articleView); 
            }
            else
            {
                return RedirectToAction("AccessDenied", "AdminHome");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ArticleViewModel articleView, HttpPostedFileBase titleImage)
        {
            CheckAddressNameAvailability(articleView.AddressName, articleView.Id);
            if (ModelState.IsValid)
            {
                var article = _modelMapper.Map<ArticleViewModel, Article>(articleView);
                if (await UserCanEditArticle(article))
                {
                    article.Tags = TagStringToList(articleView.TagsString);
                    article.LastChangedTime = DateTime.Now;
                    article.Body = Regex.Replace(article.Body, @"=([0-9])+px", "");
                    SaveUploadedImage(article, titleImage);
                    _articleRepo.Update(article);
                    return RedirectToAction("Index", "AdminHome");
                }
                else
                {
                    return RedirectToAction("AccessDenied", "AdminHome");
                }
            }
            ViewBag.Action = ActionType.EditArticle;
            return View("ArticleEditor", articleView);
        }

        private string TagListToString(ICollection<Tag> tags)
        {
            if (tags.Count == 0)
                return String.Empty;
            return String.Join<string>(",", tags.Select(tag => tag.Name));
        }

        private ICollection<Tag> TagStringToList(string tagString)
        {
            List<Tag> tags = new List<Tag>();
            if (!String.IsNullOrWhiteSpace(tagString))
            {
                var tagArray = tagString.Split(',').Distinct(StringComparer.OrdinalIgnoreCase);
                foreach (var s in tagArray)
                {
                    if (!String.IsNullOrWhiteSpace(s))
                    {
                        string name = s.Trim();
                        Tag t = _tagsRepo.GetByName(name);
                        if (null == t)
                        {
                            t = _tagsRepo.Add(new Tag { Name = name, AddressName = name });
                        }
                        tags.Add(t);
                    }
                }
            }
            return tags;
        }

        private void SaveUploadedImage(Article article, HttpPostedFileBase image)
        {
            string newPath;
            string oldPath = article.TitleImagePath;
            bool pathChanged = !isOldImagePathRelevant(oldPath, article.AddressName);
            FileInfo oldImageInfo = null;
            if (pathChanged)
                oldImageInfo = new FileInfo(Server.MapPath(oldPath));
            if (null == image)
            {
                if (pathChanged)
                {   //there is an old image and article address changed => rename old image
                    newPath = String.Format("~/Content/Images/Articles/{0}{1}",
                                        article.AddressName,
                                        oldImageInfo.Extension);
                    oldImageInfo.MoveTo(Server.MapPath(newPath));
                }
                else
                {
                    if (null == oldPath)
                        article.TitleImagePath = "";
                    return;
                }
            }
            else
            {   //there is a new image => save new image
                FileInfo newImageInfo = new FileInfo(image.FileName);
                newPath = String.Format("~/Content/Images/Articles/{0}{1}",
                                            article.AddressName,
                                            newImageInfo.Extension);
                image.SaveAs(Server.MapPath(newPath));

                if (pathChanged)
                {   //path changed and there is an old image => delete old image
                    oldImageInfo.Delete();
                }
            }
            article.TitleImagePath = newPath;
        }

        public JsonResult ValidateAddressNameAvailability(string AddressName, int Id)
        {
            if (isAddressNameAvailable(AddressName, Id))
                return Json("true", JsonRequestBehavior.AllowGet);
            else
                return Json(String.Format("Адрес {0} уже принадлежит другой статье", AddressName), JsonRequestBehavior.AllowGet);
        }

        private void CheckAddressNameAvailability(string addressName, int id)
        {
            if (!isAddressNameAvailable(addressName, id))
                ModelState.AddModelError("addressName", String.Format("Адрес {0} уже принадлежит другой статье", addressName));
        }

        private bool isAddressNameAvailable(string addressName, int id)
        {
            var existingArticle = _articleRepo.GetByAddressName(addressName);
            return (null == existingArticle || existingArticle.Id == id);
        }

        private bool isOldImagePathRelevant(string imagePath, string articleAddressName)
        {
            if (String.IsNullOrEmpty(imagePath))

NewsDotNet.WebUI/Areas/Admin/Views/AdminArticles/ArticleEditor.cshtml
@using NewsDotNet.WebUI.Areas.Admin.Controllers
@model NewsDotNet.WebUI.Areas.Admin.Models.ArticleViewModel

@{
    ActionType action = ViewBag.Action;
    ViewBag.Title = action == ActionType.NewArticle ? "Новая статья" : "Редактирование статьи";
}

@section styles
{
    <link rel="stylesheet" href="~/Content/Styles/article-editor.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/Styles/jquery-ui-1.11.4.min.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/jquery-ui-1.9.2.custom/css/black-tie/jquery-ui-1.9.2.custom.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/jquery-tags-input/jquery.tagsinput.min.css" />
}

@if (action == ActionType.EditArticle)
{
    <div id="alert-box" role="alert">
        <label id="locker-message">@ViewBag.LockerMessage</label>
    </div>
}
<div>
@using (Html.BeginForm(action == ActionType.NewArticle ? "New" : "Edit",
                        "AdminArticles",
                        FormMethod.Post,
                        new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal container">
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.CreatedTime)
        @Html.HiddenFor(model => model.TitleImagePath)
        @Html.HiddenFor(model => model.State)
        @Html.HiddenFor(model => model.AuthorId)
        
        @{bool isImagePresent = !String.IsNullOrEmpty(Model.TitleImagePath);}

        <div class="form-group">
            <label class="control-label col-xs-6 col-sm-2">Заголовок</label>
            <div class="col-xs-12 col-sm-9">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-xs-6 col-sm-2">Адрес</label>
            <div class="col-xs-12 col-sm-9">
                @Html.EditorFor(model => model.AddressName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-xs-6 col-sm-2">Изображение</label>
            <div class="col-xs-12 col-sm-9">
                <div class="row" id="previewRow" @if (!isImagePresent) { <text> hidden="hidden" </text> }>
                    <div class="col-xs-12 col-sm-6 col-md-5">
                        <img id="uploadPreview" 
                             @if (isImagePresent) { <text> src="@Url.Content(Model.TitleImagePath)" </text>  } />
                    </div>
                </div>
                <div class="input-group">
                    <span class="input-group-btn">
                        <span class="btn btn-primary btn-file">
                            Выберите файл...
                            <input type="file" name="titleImage" id="titleImage" accept=".jpg,.png,.jpeg,.gif" onchange="PreviewImage();" />
                        </span>
                    </span>
                    <input type="text" id="titleText" class="form-control" readonly>
                </div>
                @Html.ValidationMessageFor(model => model.TitleImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-xs-6 col-sm-2">Тело статьи</label>
            <div class="col-xs-12 col-sm-9">
                @Html.TextAreaFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-xs-6 col-sm-2">Теги</label>
            <div class="col-xs-12 col-sm-9">
                @Html.EditorFor(model => model.TagsString, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.TagsString, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-xs-offset-2 col-xs-9">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
</div>
<div>
    @Html.ActionLink("Вернуться к списку", "Index", "AdminHome")
</div>

@section scripts
{
    <script src="~/Content/ckeditor/ckeditor.js"></script>
    <script src="~/Content/jquery-tags-input/jquery.tagsinput.min.js"></script>
    <script src="~/Scripts/bootstrap-maxlength.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.11.4.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    @if (action == ActionType.EditArticle)
    {
        <script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>
        <script src="~/signalr/hubs"></script>
        <script src="~/Scripts/article-locker.js"></script> //should be included before article-editor.js
    }

    <script src="~/Scripts/article-editor.js"></script>
}